name: BG Price Tracker

on:
  schedule:
    - cron: "*/5 * * * *"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout del codice
        uses: actions/checkout@v3
        with:
          persist-credentials: true  # ← importante

      - name: Configura Git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: Installa dipendenze
        run: pip install -r requirements.txt

      - name: Esegui script
        run: python main.py

      - name: Commit e push modifiche
        run: |
          git add Lista.json storico_prezzi.csv
          git commit -m "Aggiorna soglia minima e storico prezzi" || echo "Nessuna modifica da salvare"
          git push origin main
